# Generated by Django 6.0.6 on 2026-06-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
