# Generated by Django 6.0.6 on 2026-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contact_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(blank=True, default=0, max_length=15),
            preserve_default=False,
        ),
    ]
